#!/bin/sh
echo test
./dist/build/hexdump/hexdump d1.bin | md5sum
echo 7d80d50d57ff09ac698899f76a078b5a "<--" should be
time ./dist/build/hexdump/hexdump d1.bin >/dev/null

#time /home/ubuntu/tt69/hexdump/.stack-work/dist/x86_64-linux/Cabal-2.2.0.1/build/hexdump/hexdump d1.bin | wc
# 200MBytes per second
# output bytes 1103374297
# time 5.25
